<?php
// ATTENTION - ATTENTION config.php - Automatically generated by the CactusDrop installer

// --- Database configuration ---
define('DB_HOST', 'localhost');
define('DB_USER', 'YOUR DB USERNAME');
define('DB_PASS', 'YOUR DB PASS');
define('DB_NAME', 'YOUR DB NAME');

// --- App configuration ---
define('APP_URL', 'https://schuttehub.de/v2');
define('UPLOAD_DIR', __DIR__ . '/uploads/');
date_default_timezone_set('Europe/Berlin'); //Change timezone

// --- File upload limits (can be customized here) ---
define('FILE_EXPIRATION_HOURS', 24); // Gültigkeit in Stunden
define('MAX_FILE_SIZE', 100 * 1024 * 1024); // 100 MB

// --- Allowed file types ---
// IMPORTANT: A configuration that is too open can be a security risk.
define('ALLOWED_MIME_TYPES', [
    // Photo
    'image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml',
    // Documents
    'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.presentation',
    'text/plain', 'text/csv',
    // Archiv
    'application/zip', 'application/x-rar-compressed', 'application/x-7z-compressed', 'application/x-tar', 'application/gzip',
    // Audio/Video
    'video/mp4', 'video/quicktime', 'video/x-msvideo', 'video/x-matroska',
    'audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/flac',
    // other
    'application/json', 'application/xml', 'application/octet-stream'
]);

// --- Auxiliary functions ---

/**
 * Sends a standardized JSON error response and terminates the script.
 */
function send_json_error($message, $statusCode = 500) {
    http_response_code($statusCode);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['status' => 'error', 'message' => $message]);
    exit;
}

/**
 * Cleans a file name to save it securely.
 */
function sanitize_filename($filename) {
    $basename = basename($filename);
    $sanitized = preg_replace('/[^\pL\pN\s._-]/u', '_', $basename);
    $sanitized = trim($sanitized, '._-');
    if (empty($sanitized)) {
        return 'unbenannte_datei';
    }
    return $sanitized;
}

/**
 * Establishes a database connection and returns it.
 */
function get_db_connection() {
    mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
    try {
        $conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
        $conn->set_charset('utf8mb4');
        return $conn;
    } catch (mysqli_sql_exception $e) {
        error_log('DB Connection Error: ' . $e->getMessage());
        send_json_error('Fehler beim Verbinden mit der Datenbank.', 500);
    }
}
